services:
  - type: web
    name: tigerterritory
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false  # Set this in the Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in the Render dashboard